[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"
autor = "443486977@qq.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"